name: SiteIntegration
version: "${project.version}"
main: org.example.mc.siteintegration.SiteIntegration
api-version: "1.20"
commands:
  trade:
    description: Виконати різні торгові операції
    usage: /<command> <subcommand> [amount]
